#!/bin/bash
# Author: Steven Shiau <steven _at_ nchc org tw>
# License: GPL
# Description: Program to start saving or restoring image in Clonezilla live.

# Load DRBL setting and functions
DRBL_SCRIPT_PATH="${DRBL_SCRIPT_PATH:-/usr/share/drbl}"

. $DRBL_SCRIPT_PATH/sbin/drbl-conf-functions
. /etc/drbl/drbl-ocs.conf
. $DRBL_SCRIPT_PATH/sbin/ocs-functions

# load the setting for clonezilla live.
[ -e /etc/ocs/ocs-live.conf ] && . /etc/ocs/ocs-live.conf

# Functions
USAGE() {
    echo "$ocs - Program to start saving or restoring image in Clonezilla live"
    echo "Usage:"
    echo "To run $ocs:"
    echo "$ocs"
    echo "Ex:"
    echo "To start saving or restoring image in Clonezilla live, run"
    echo "   $ocs"
    echo "If what you want is just saving, use \"ocs-live-save\" instead of this program."
    echo "If what you want is just restoring, use \"ocs-live-restore\" instead of this program."
} # end of USAGE

####################
### Main program ###
####################

ocs=`basename $0`
#
check_if_root
#
while [ $# -gt 0 ]; do
 case "$1" in
   -*)     echo "${0}: ${1}: invalid option" >&2
           USAGE >& 2
           exit 2 ;;
   *)      break ;;
 esac
done

# Get the live media mount point.
get_live_media_mnt_point ##Sets LIVE_MEDIA env variable by funding squashfs location on the medium, or if its using PXE it will parse the path to find it. Defined in ocs-functions.

# prepare the clonezilla live environment.
##JAYSON: Function from ocs-functions 10379. This makes sure the environment is properly setup and will prompt for language if it was not set in ocs-live.conf.
##This was already set in preperation phase.
#Calls 4-MENU with option to start clonezilla live or enter shell. Selecting shell will exit script with code 99..
ocs-live-env-prepare 
# "-n" was added since we will run show-general-ocs-live-prompt after command clonezilla. If shell selected, returns error code 99
LC_ALL=$ocs_lang clonezilla -n
rc=$?

##JAYSON This is the post program operation and will display information and instruction depending on the previous action taken based on environment variables. 
##For Device to Image option this simply informs you how to run again and waits for user input.
##If network mode was used it will print additional information prior.
# Show prompt when in interactive mode
if [ -e /var/lib/clonezilla/ocs-vars ]; then
  . /var/lib/clonezilla/ocs-vars
  # Only in interactive mode, and if it's not reboot or poweroff, the prompt is shown.
  if [ "$ocs_sr_mode" = "interactive" ]; then
    # 1. Show removing one of disks after cloning.
    if [ "$ocs_cmd" = "ocs-onthefly" ]; then
      [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
      echo "$msg_remove_source_or_destination_disk_after_cloning"
      echo "$msg_2_identical_systems_will_confuse_restored_os"
      [ "$BOOTUP" = "color" ] && $SETCOLOR_WARNING
    fi
    # 2. show prompt about re-run and poweroff
    case "$postaction" in
      reboot|poweroff) true;;
      *) show-general-ocs-live-prompt;; ##In ocs-functions. This will show "If you want to use Clonezilla again" followed by instructions, then will pause for user input.
    esac
  fi
fi

exit $rc
